### ISSUE TITLE
Run too slow

### ISSUE THREAD

**Issue by MatthewCYM** [ZexinLee/LeetCode#1]
Why are you code so inefficient?

**Comment by MatthewCYM** [comment]
I agree that too.

**Comment by ZexinLee** [comment]
@MatthewCYM For most of cases, reducing time complexity and space complexity are difficult to achieve at the same time. At the beginning of the problem solving, we will usually try to use the brute force algorithm to achieve the submission of observations to pass all test cases. Therefor, each solution provides the current optimal solution for Leetcode and you can try reading them to understand efficient solutions.
